# Generated by Django 5.2.4 on 2025-11-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_customer_review_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='read_date',
            new_name='reading_date',
        ),
    ]
